data <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, stringsAsFactors = FALSE)
data[,"Date"] <- as.Date(data[,"Date"],format = "%d/%m/%Y")
sdata<-subset(data,Date == "2007-02-01" | Date == "2007-02-02")
datet<-strptime(paste(sdata$Date,sdata$Time,sep = " "), "%Y-%m-%d %H:%M:%S" )
GlobActPow<-as.numeric(sdata[,"Global_active_power"])
png("plot2.png",width = 480, height = 480)
plot(datet,GlobActPow,type = "l",xlab = " ",ylab = "Global Active Power (kilowatts)")
dev.off()
